SUPABASE_URL = "https://zxbgxcfknbwedlvhqdru.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4Ymd4Y2ZrbmJ3ZWRsdmhxZHJ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg0MTg1ODIsImV4cCI6MjA2Mzk5NDU4Mn0.o_Uv9mc2tvmcSzGcA0lPO7DPmyaMO7yjxP1osWDV4y4"
